# -*- coding: utf-8 -*-
"""initial_parser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oi2HXQUQ_bLrJCRv6FBrN62Q63txcLFs
"""

import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau, CSVLogger, TensorBoard
from tensorflow.keras.optimizers import Adam
from dataclasses import dataclass
from runner import *
from trainer import *
from splitter import *
from data_provider import *
from custom_models import *
from custom_metrics import *
from custom_losses import *
from iterstrat.ml_stratifiers import MultilabelStratifiedKFold
from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit
import os
import random
from tensorflow.keras.layers.experimental import preprocessing 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import albumentations as A
import numpy as np
from keras.models import Model
from keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D
from keras.layers import BatchNormalization
from keras.layers.core import SpatialDropout2D, Activation
from tensorflow.keras.applications import EfficientNetB0
from keras import backend as K
from keras.layers.merge import concatenate
from keras.utils.data_utils import get_file
from tensorflow import keras
import segmentation_models as sm
import cv2
import datetime
from segmentation_models.losses import bce_jaccard_loss
from pathlib import Path

class initial_parser_imseg():
    def __init__(self, input_data_path, input_label_path, input_class_count):
      self.data_path = input_data_path
      self.label_path = input_label_path
      self.class_count = input_class_count
      self.item_list = os.listdir(self.data_path)


    def class_labels(self, items):
      class_labels = []
      for name in items:
        cls_labels_for_img = np.zeros(self.class_count)
        img = cv2.imread(str(Path(self.label_path) / Path(name)))
        cls_labels_for_img[np.unique(img)] = 1
        class_labels.append(cls_labels_for_img)
      return class_labels


    def get_list(self):
      return [self.item_list, self.class_labels(self.item_list)]
